FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y software-properties-common
RUN add-apt-repository ppa:ondrej/php -y
RUN add-apt-repository ppa:ondrej/apache2 -y

RUN apt-get update
RUN apt-get install -y openssl apache2 mailutils unzip mcrypt postfix libssl-dev cron
RUN apt-get install -y php5.6 php5.6-mysql php5.6-gd php5.6-dev php5.6-cli php5.6-curl php5.6-xml php5.6-mbstring php-pear php-mongodb php5.6-bz2 php5.6-common php5.6-mcrypt php5.6-zip
RUN apt-add-repository ppa:mosquitto-dev/mosquitto-ppa -y
RUN apt-get install -y mosquitto-clients libmosquitto-dev
RUN apt-get clean && apt-get autoclean

#default ubuntu:20.04 has php verison 8
RUN rm /etc/alternatives/php && ln -s /usr/bin/php5.6 /etc/alternatives/php
#install mono extension
RUN pecl install mongo

#install mosquitto
RUN pecl install mosquitto-alpha

#add php ini file
COPY ./scripts/php_apach2.ini /etc/php/5.6/apach2/
COPY ./scripts/php_cli.ini /etc/php/5.6/cli


#copy dec/enc for php to decode src
COPY ./scripts/med_enc /usr/sbin/
COPY ./scripts/med_dec /usr/sbin/
COPY ./scripts/descrypt.sh /tmp

RUN mkdir -p /package
RUN mkdir -p /webserv
COPY ./src/BEMS_2.0.zip.nc /package
COPY ./src/CoreModules.zip.nc /package
# add decrypt src code for test
#ADD ./webserv.tar /
RUN /tmp/descrypt.sh
